// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This file has been auto-generated. Do not edit by hand.
// Instead open Developer Command prompt and run: TextTransform FileName.tt
// Or set AllowTlsCipherSuiteGeneration=true and open VS and edit there directly

// This line is needed so that file compiles both as a T4 template and C# file

using System.Diagnostics;
using System.Security.Authentication;

namespace System.Net.Security
{
    internal partial struct SslConnectionInfo
    {
        private void MapCipherSuite(TlsCipherSuite cipherSuite)
        {
            TlsCipherSuite = cipherSuite;
            KeyExchKeySize = 0;

            int index = Array.BinarySearch(s_cipherSuites, cipherSuite);
            Debug.Assert(index >= 0);

            index *= 4;
            KeyExchangeAlg = TlsCipherSuiteData[index];
            DataCipherAlg = TlsCipherSuiteData[index + 1];
            DataKeySize = TlsCipherSuiteData[index + 2];
            DataHashAlg = TlsCipherSuiteData[index + 3];
            DataHashKeySize = GetHashSize(DataHashAlg);

            static int GetHashSize(int hash)
            {
                switch ((HashAlgorithmType)hash)
                {
                    case HashAlgorithmType.None:
                        return 0;
                    case HashAlgorithmType.Md5:
                        return 128;
                    case HashAlgorithmType.Sha1:
                        return 160;
                    case HashAlgorithmType.Sha256:
                        return 256;
                    case HashAlgorithmType.Sha384:
                        return 384;
                    case HashAlgorithmType.Sha512:
                        return 512;
                    default:
                        throw new ArgumentOutOfRangeException(hash.ToString());
                }
            }
        }

        // Or just a switch from TlsCipherSuite => index
        private static readonly TlsCipherSuite[] s_cipherSuites = Enum.GetValues<TlsCipherSuite>();

        private static ReadOnlySpan<int> TlsCipherSuiteData => new[]
        {
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Rc4, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Rc2, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Des, 56, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc2, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc4, 40, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Des, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc2, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc4, 40, (int)HashAlgorithmType.Md5,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Rc4, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.TripleDes, 168, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha1,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Null, 0, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 128, (int)HashAlgorithmType.Sha256,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.Sha384,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.None, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.RsaKeyX, (int)CipherAlgorithmType.None, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes256, 256, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
            (int)ExchangeAlgorithmType.DiffieHellman, (int)CipherAlgorithmType.Aes128, 128, (int)HashAlgorithmType.None,
        };
    }
}
